name: ci-go-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22.1
      - run: go test
      - run: go run sum.go
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1